### ISSUE TITLE
Needs a way to skip TikTok submissions

### ISSUE THREAD

**Issue by neverstop123** [rolyli/lonk-dl#7]
TikTok submissions makes this error when extracting a redditors images.

Attempting to extract from https://vm.tiktok.com/xxxxx.
Traceback (most recent call last):
  File "lonk_dl.py", line 103, in <module>
    main()
  File "lonk_dl.py", line 90, in main
    with open(determine_path_or_file(args.path, filename), permissions) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\xxxx'

**Comment by rolyli** [comment]
Hi, which version are you using? I've tested with the latest commit and `vm.tiktok.com/kurynt` and it gets skipped with this status: `[kurynt] Skipping as url type is html text.`

**Comment by rolyli** [comment]
I tidied up how lonk-dl filters for non-image links. Hopefully it works fine now.
